CONFIG_PRINTK=y
CONFIG_LOG=n
CONFIG_ASSERT=n

# IPC
CONFIG_EVENTS=y   

#MEM
CONFIG_HEAP_MEM_POOL_SIZE=2048

#BT
CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y

# update data len
CONFIG_BT_DATA_LEN_UPDATE=y
CONFIG_BT_USER_DATA_LEN_UPDATE=y
CONFIG_BT_CTLR_DATA_LENGTH_MAX=251
CONFIG_BT_BUF_ACL_TX_SIZE=502
CONFIG_BT_BUF_ACL_RX_SIZE=502
CONFIG_BT_L2CAP_TX_MTU=498

# update phy param
CONFIG_BT_PHY_UPDATE=y
CONFIG_BT_USER_PHY_UPDATE=y
CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_CTLR_PHY_CODED=y

# ble tx power
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y
CONFIG_BT_LL_SW_SPLIT=y

# Set preferred values based on BT_BAP_CONN_PARAM_RELAXED
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=30
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_TIMEOUT=400

# gpio enable
CONFIG_GPIO=y

# i2c enable
CONFIG_I2C=y
CONFIG_I2C_NRFX=y

# uart enable
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y

# disable watchdog
CONFIG_WATCHDOG=y

# user custom function
CONFIG_AS201_IMU=n
CONFIG_LD2410C_DDRS=n
CONFIG_AHT20_TS=y
CONFIG_BMP280_PS=y
CONFIG_HRBO=y
CONFIG_BLINK=y
CONFIG_DEBUG_UART=n
CONFIG_BT_CRS=y

# Enable MCUmgr and dependencies.
CONFIG_KERNEL_BIN_NAME="V_1_0_11"
CONFIG_BT_DEVICE_NAME="CRS_V_1_0_11"
CONFIG_BOOTLOADER_MCUBOOT=y
CONFIG_MCUMGR=y
CONFIG_MCUMGR_TRANSPORT_BT=y
CONFIG_MCUMGR_GRP_IMG=y
CONFIG_MCUMGR_GRP_OS=y
CONFIG_MCUMGR_TRANSPORT_BT_REASSEMBLY=y
CONFIG_MCUMGR_GRP_OS_MCUMGR_PARAMS=y

# speed
CONFIG_MCUMGR_TRANSPORT_BT_CONN_PARAM_CONTROL=y
CONFIG_MCUMGR_TRANSPORT_NETBUF_SIZE=2475

# mmg
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_STREAM_FLASH=y
CONFIG_IMG_MANAGER=y
CONFIG_NET_BUF=y
CONFIG_ZCBOR=y

