#drivers status

#GPIO
CONFIG_GPIO=y

#UART
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y

# I2C 
CONFIG_I2C=y

# STM32 I2C
CONFIG_I2C_STM32=n
CONFIG_I2C_STM32_V2_TIMING=n

# NRF I2C
CONFIG_I2C_NRFX=y

# SPI 
CONFIG_SPI=n

# STM32 SPI
CONFIG_SPI_STM32=n

# NRF SPI

# devices status
CONFIG_CUSTOM_BLINKY=y
CONFIG_CUSTOM_UART=n
CONFIG_BMP280_PS=y
CONFIG_CUSTOM_SPI=n
